# src/cloud_harvester/schema.py
"""Column definitions matching classic_analyser's XLSX format exactly."""
from dataclasses import dataclass, field


@dataclass
class ColumnDef:
    header: str
    field: str
    data_type: str = "string"  # string, number, boolean, date, currency, array, bytes


@dataclass
class ResourceSchema:
    worksheet_name: str
    domain: str
    resource_type: str
    columns: list[ColumnDef] = field(default_factory=list)


# ──────────────────────────────────────────────
# CLASSIC INFRASTRUCTURE SCHEMAS (~25 types)
# ──────────────────────────────────────────────

CLASSIC_SCHEMAS: dict[str, ResourceSchema] = {
    "virtualServers": ResourceSchema(
        worksheet_name="vVirtualServers",
        domain="classic",
        resource_type="virtualServers",
        columns=[
            ColumnDef("ID", "id", "number"),
            ColumnDef("Hostname", "hostname"),
            ColumnDef("Domain", "domain"),
            ColumnDef("FQDN", "fqdn"),
            ColumnDef("Primary IP", "primaryIp"),
            ColumnDef("Backend IP", "backendIp"),
            ColumnDef("CPU", "maxCpu", "number"),
            ColumnDef("Memory (MB)", "maxMemory", "number"),
            ColumnDef("Status", "status"),
            ColumnDef("Power State", "powerState"),
            ColumnDef("Datacenter", "datacenter"),
            ColumnDef("OS", "os"),
            ColumnDef("Hourly Billing", "hourlyBilling"),
            ColumnDef("Create Date", "createDate", "date"),
            ColumnDef("Classic Monthly Fee", "recurringFee", "currency"),
            ColumnDef("Cost Basis", "costBasis"),
            ColumnDef("Notes", "notes"),
            ColumnDef("Private Only", "privateNetworkOnly"),
            ColumnDef("Local Disk", "localDisk"),
            ColumnDef("Start CPUs", "startCpus", "number"),
            ColumnDef("Modified", "modifyDate", "date"),
            ColumnDef("Dedicated", "dedicated"),
            ColumnDef("Placement Group", "placementGroupId", "number"),
            ColumnDef("Tags", "tags"),
            ColumnDef("Disk (GB)", "diskGb", "number"),
            ColumnDef("VLANs", "networkVlans"),
        ],
    ),
    "bareMetal": ResourceSchema(
        worksheet_name="vBareMetal",
        domain="classic",
        resource_type="bareMetal",
        columns=[
            ColumnDef("ID", "id", "number"),
            ColumnDef("Hostname", "hostname"),
            ColumnDef("Domain", "domain"),
            ColumnDef("FQDN", "fqdn"),
            ColumnDef("Serial Number", "serialNumber"),
            ColumnDef("Primary IP", "primaryIp"),
            ColumnDef("Backend IP", "backendIp"),
            ColumnDef("Cores", "cores", "number"),
            ColumnDef("Memory (GB)", "memory", "number"),
            ColumnDef("Datacenter", "datacenter"),
            ColumnDef("OS", "os"),
            ColumnDef("Classic Monthly Fee", "recurringFee", "currency"),
            ColumnDef("Provision Date", "provisionDate", "date"),
            ColumnDef("Power Supplies", "powerSupplyCount", "number"),
            ColumnDef("Gateway Member", "gatewayMember"),
            ColumnDef("VMware Role", "vmwareRole"),
            ColumnDef("Notes", "notes"),
            ColumnDef("Hard Drives", "hardDrives"),
            ColumnDef("Network Components", "networkComponents"),
            ColumnDef("VLANs", "networkVlans"),
            ColumnDef("Tags", "tags"),
        ],
    ),
    "vlans": ResourceSchema(
        worksheet_name="vVLANs",
        domain="classic",
        resource_type="vlans",
        columns=[
            ColumnDef("ID", "id", "number"),
            ColumnDef("VLAN Number", "vlanNumber", "number"),
            ColumnDef("Name", "name"),
            ColumnDef("Network Space", "networkSpace"),
            ColumnDef("Primary Router", "primaryRouter"),
            ColumnDef("Datacenter", "datacenter"),
            ColumnDef("Subnet Count", "subnetCount", "number"),
            ColumnDef("Firewall Components", "firewallComponents", "number"),
            ColumnDef("Gateway", "gateway"),
        ],
    ),
    "subnets": ResourceSchema(
        worksheet_name="vSubnets",
        domain="classic",
        resource_type="subnets",
        columns=[
            ColumnDef("ID", "id", "number"),
            ColumnDef("Network", "networkIdentifier"),
            ColumnDef("CIDR", "cidr", "number"),
            ColumnDef("Type", "subnetType"),
            ColumnDef("Gateway", "gateway"),
            ColumnDef("Broadcast", "broadcastAddress"),
            ColumnDef("Usable IPs", "usableIpAddressCount", "number"),
            ColumnDef("Total IPs", "totalIpAddresses", "number"),
            ColumnDef("VLAN", "vlanNumber", "number"),
            ColumnDef("Datacenter", "datacenter"),
        ],
    ),
    "gateways": ResourceSchema(
        worksheet_name="vGateways",
        domain="classic",
        resource_type="gateways",
        columns=[
            ColumnDef("ID", "id", "number"),
            ColumnDef("Name", "name"),
            ColumnDef("Network Space", "networkSpace"),
            ColumnDef("Status", "status"),
            ColumnDef("Public IP", "publicIp"),
            ColumnDef("Private IP", "privateIp"),
            ColumnDef("Members", "memberCount", "number"),
            ColumnDef("Inside VLANs", "insideVlanCount", "number"),
        ],
    ),
    "firewalls": ResourceSchema(
        worksheet_name="vFirewalls",
        domain="classic",
        resource_type="firewalls",
        columns=[
            ColumnDef("ID", "id", "number"),
            ColumnDef("Primary IP", "primaryIpAddress"),
            ColumnDef("Type", "firewallType"),
            ColumnDef("VLAN", "vlanNumber", "number"),
            ColumnDef("Datacenter", "datacenter"),
            ColumnDef("Classic Monthly Fee", "recurringFee", "currency"),
            ColumnDef("Rules", "ruleCount", "number"),
        ],
    ),
    "securityGroups": ResourceSchema(
        worksheet_name="vSecurityGroups",
        domain="classic",
        resource_type="securityGroups",
        columns=[
            ColumnDef("ID", "id", "number"),
            ColumnDef("Name", "name"),
            ColumnDef("Description", "description"),
            ColumnDef("Created", "createDate", "date"),
            ColumnDef("Modified", "modifyDate", "date"),
            ColumnDef("Rules", "ruleCount", "number"),
            ColumnDef("Bindings", "bindingCount", "number"),
        ],
    ),
    "securityGroupRules": ResourceSchema(
        worksheet_name="vSecurityGroupRules",
        domain="classic",
        resource_type="securityGroupRules",
        columns=[
            ColumnDef("Security Group ID", "securityGroupId", "number"),
            ColumnDef("Security Group Name", "securityGroupName"),
            ColumnDef("Rule ID", "id", "number"),
            ColumnDef("Direction", "direction"),
            ColumnDef("Protocol", "protocol"),
            ColumnDef("Port Min", "portRangeMin", "number"),
            ColumnDef("Port Max", "portRangeMax", "number"),
            ColumnDef("Remote IP", "remoteIp"),
            ColumnDef("Remote Group ID", "remoteGroupId", "number"),
        ],
    ),
    "loadBalancers": ResourceSchema(
        worksheet_name="vLoadBalancers",
        domain="classic",
        resource_type="loadBalancers",
        columns=[
            ColumnDef("ID", "id", "number"),
            ColumnDef("Name", "name"),
            ColumnDef("IP Address", "ipAddress"),
            ColumnDef("Type", "loadBalancerType"),
            ColumnDef("Connection Limit", "connectionLimit", "number"),
            ColumnDef("Classic Monthly Fee", "recurringFee", "currency"),
            ColumnDef("Virtual Servers", "virtualServers"),
        ],
    ),
    "blockStorage": ResourceSchema(
        worksheet_name="vBlockStorage",
        domain="classic",
        resource_type="blockStorage",
        columns=[
            ColumnDef("ID", "id", "number"),
            ColumnDef("Username", "username"),
            ColumnDef("Capacity (GB)", "capacityGb", "number"),
            ColumnDef("IOPS", "iops"),
            ColumnDef("Storage Type", "storageType"),
            ColumnDef("Tier", "storageTierLevel"),
            ColumnDef("Target IP", "targetIp"),
            ColumnDef("LUN ID", "lunId"),
            ColumnDef("Snapshot (GB)", "snapshotCapacityGb", "number"),
            ColumnDef("Classic Monthly Fee", "recurringFee", "currency"),
            ColumnDef("Create Date", "createDate", "date"),
            ColumnDef("Notes", "notes"),
            ColumnDef("Allowed VSIs", "allowedVirtualGuests"),
            ColumnDef("Allowed Hardware", "allowedHardware"),
            ColumnDef("Replication Partners", "replicationPartners"),
        ],
    ),
    "fileStorage": ResourceSchema(
        worksheet_name="vFileStorage",
        domain="classic",
        resource_type="fileStorage",
        columns=[
            ColumnDef("ID", "id", "number"),
            ColumnDef("Username", "username"),
            ColumnDef("Capacity (GB)", "capacityGb", "number"),
            ColumnDef("IOPS", "iops"),
            ColumnDef("Storage Type", "storageType"),
            ColumnDef("Tier", "storageTierLevel"),
            ColumnDef("Target IP", "targetIp"),
            ColumnDef("Mount Address", "mountAddress"),
            ColumnDef("Snapshot (GB)", "snapshotCapacityGb", "number"),
            ColumnDef("Classic Monthly Fee", "recurringFee", "currency"),
            ColumnDef("Create Date", "createDate", "date"),
            ColumnDef("Notes", "notes"),
            ColumnDef("Allowed VSIs", "allowedVirtualGuests"),
            ColumnDef("Allowed Hardware", "allowedHardware"),
            ColumnDef("Replication Partners", "replicationPartners"),
        ],
    ),
    "objectStorage": ResourceSchema(
        worksheet_name="vObjectStorage",
        domain="classic",
        resource_type="objectStorage",
        columns=[
            ColumnDef("ID", "id", "number"),
            ColumnDef("Username", "username"),
            ColumnDef("Storage Type", "storageType"),
            ColumnDef("Capacity (GB)", "capacityGb", "number"),
            ColumnDef("Bytes Used", "bytesUsed", "number"),
            ColumnDef("Classic Monthly Fee", "recurringFee", "currency"),
            ColumnDef("Create Date", "createDate", "date"),
        ],
    ),
    "sslCertificates": ResourceSchema(
        worksheet_name="vSSLCertificates",
        domain="classic",
        resource_type="sslCertificates",
        columns=[
            ColumnDef("ID", "id", "number"),
            ColumnDef("Common Name", "commonName"),
            ColumnDef("Organization", "organizationName"),
            ColumnDef("Valid From", "validityBegin", "date"),
            ColumnDef("Validity (Days)", "validityDays", "number"),
            ColumnDef("Valid Until", "validityEnd", "date"),
            ColumnDef("Create Date", "createDate", "date"),
            ColumnDef("Notes", "notes"),
        ],
    ),
    "sshKeys": ResourceSchema(
        worksheet_name="vSSHKeys",
        domain="classic",
        resource_type="sshKeys",
        columns=[
            ColumnDef("ID", "id", "number"),
            ColumnDef("Label", "label"),
            ColumnDef("Fingerprint", "fingerprint"),
            ColumnDef("Create Date", "createDate", "date"),
            ColumnDef("Modify Date", "modifyDate", "date"),
            ColumnDef("Notes", "notes"),
        ],
    ),
    "dnsDomains": ResourceSchema(
        worksheet_name="vDNSDomains",
        domain="classic",
        resource_type="dnsDomains",
        columns=[
            ColumnDef("ID", "id", "number"),
            ColumnDef("Name", "name"),
            ColumnDef("Serial", "serial", "number"),
            ColumnDef("Update Date", "updateDate", "date"),
            ColumnDef("Record Count", "recordCount", "number"),
        ],
    ),
    "dnsRecords": ResourceSchema(
        worksheet_name="vDNSRecords",
        domain="classic",
        resource_type="dnsRecords",
        columns=[
            ColumnDef("Domain ID", "domainId", "number"),
            ColumnDef("Domain", "domainName"),
            ColumnDef("ID", "id", "number"),
            ColumnDef("Host", "host"),
            ColumnDef("Type", "type"),
            ColumnDef("Data", "data"),
            ColumnDef("TTL", "ttl", "number"),
            ColumnDef("Priority", "priority", "number"),
        ],
    ),
    "images": ResourceSchema(
        worksheet_name="vImages",
        domain="classic",
        resource_type="images",
        columns=[
            ColumnDef("ID", "id", "number"),
            ColumnDef("Name", "name"),
            ColumnDef("Global ID", "globalIdentifier"),
            ColumnDef("Note", "note"),
            ColumnDef("Created", "createDate", "date"),
            ColumnDef("Status", "status"),
            ColumnDef("Datacenter", "datacenter"),
            ColumnDef("Parent ID", "parentId", "number"),
        ],
    ),
    "dedicatedHosts": ResourceSchema(
        worksheet_name="vDedicatedHosts",
        domain="classic",
        resource_type="dedicatedHosts",
        columns=[
            ColumnDef("ID", "id", "number"),
            ColumnDef("Name", "name"),
            ColumnDef("Created", "createDate", "date"),
            ColumnDef("Datacenter", "datacenter"),
            ColumnDef("CPU Count", "cpuCount", "number"),
            ColumnDef("Memory (GB)", "memoryCapacity", "number"),
            ColumnDef("Disk (GB)", "diskCapacity", "number"),
            ColumnDef("Guest Count", "guestCount", "number"),
        ],
    ),
    "placementGroups": ResourceSchema(
        worksheet_name="vPlacementGroups",
        domain="classic",
        resource_type="placementGroups",
        columns=[
            ColumnDef("ID", "id", "number"),
            ColumnDef("Name", "name"),
            ColumnDef("Created", "createDate", "date"),
            ColumnDef("Rule", "rule"),
            ColumnDef("Backend Router", "backendRouter"),
            ColumnDef("Guest Count", "guestCount", "number"),
        ],
    ),
    "reservedCapacity": ResourceSchema(
        worksheet_name="vReservedCapacity",
        domain="classic",
        resource_type="reservedCapacity",
        columns=[
            ColumnDef("ID", "id", "number"),
            ColumnDef("Name", "name"),
            ColumnDef("Created", "createDate", "date"),
            ColumnDef("Backend Router", "backendRouter"),
            ColumnDef("Instances", "instanceCount", "number"),
        ],
    ),
    "vpnTunnels": ResourceSchema(
        worksheet_name="vVPNTunnels",
        domain="classic",
        resource_type="vpnTunnels",
        columns=[
            ColumnDef("ID", "id", "number"),
            ColumnDef("Name", "name"),
            ColumnDef("Customer Peer IP", "customerPeerIpAddress"),
            ColumnDef("Internal Peer IP", "internalPeerIpAddress"),
            ColumnDef("P1 Auth", "phaseOneAuthentication"),
            ColumnDef("P1 Encryption", "phaseOneEncryption"),
            ColumnDef("P2 Auth", "phaseTwoAuthentication"),
            ColumnDef("P2 Encryption", "phaseTwoEncryption"),
            ColumnDef("Address Translations", "addressTranslations"),
            ColumnDef("Customer Subnets", "customerSubnets"),
            ColumnDef("Internal Subnets", "internalSubnets"),
        ],
    ),
    "billing": ResourceSchema(
        worksheet_name="vBilling",
        domain="classic",
        resource_type="billing",
        columns=[
            ColumnDef("ID", "id", "number"),
            ColumnDef("Description", "description"),
            ColumnDef("Category", "categoryCode"),
            ColumnDef("Classic Monthly Fee", "recurringFee", "currency"),
            ColumnDef("Create Date", "createDate", "date"),
            ColumnDef("Cancel Date", "cancellationDate", "date"),
            ColumnDef("Notes", "notes"),
        ],
    ),
    "users": ResourceSchema(
        worksheet_name="vUsers",
        domain="classic",
        resource_type="users",
        columns=[
            ColumnDef("ID", "id", "number"),
            ColumnDef("Username", "username"),
            ColumnDef("Email", "email"),
            ColumnDef("First Name", "firstName"),
            ColumnDef("Last Name", "lastName"),
            ColumnDef("Create Date", "createDate", "date"),
            ColumnDef("Status Date", "statusDate", "date"),
            ColumnDef("Status", "userStatus"),
            ColumnDef("Roles", "roles"),
            ColumnDef("Permissions", "permissions"),
        ],
    ),
    "eventLog": ResourceSchema(
        worksheet_name="vEventLog",
        domain="classic",
        resource_type="eventLog",
        columns=[
            ColumnDef("Event", "eventName"),
            ColumnDef("Date", "eventCreateDate", "date"),
            ColumnDef("User Type", "userType"),
            ColumnDef("User ID", "userId", "number"),
            ColumnDef("Username", "username"),
            ColumnDef("Object", "objectName"),
            ColumnDef("Object ID", "objectId", "number"),
            ColumnDef("Trace ID", "traceId"),
        ],
    ),
    "relationships": ResourceSchema(
        worksheet_name="vRelationships",
        domain="classic",
        resource_type="relationships",
        columns=[
            ColumnDef("Parent Type", "parentType"),
            ColumnDef("Parent ID", "parentId", "number"),
            ColumnDef("Parent Name", "parentName"),
            ColumnDef("Child Type", "childType"),
            ColumnDef("Child ID", "childId", "number"),
            ColumnDef("Child Name", "childName"),
            ColumnDef("Relationship Field", "relationshipField"),
        ],
    ),
}


# ──────────────────────────────────────────────
# VPC INFRASTRUCTURE SCHEMAS (~26 types)
# ──────────────────────────────────────────────

VPC_SCHEMAS: dict[str, ResourceSchema] = {
    "vpcInstances": ResourceSchema(
        worksheet_name="vVpcInstances",
        domain="vpc",
        resource_type="vpcInstances",
        columns=[
            ColumnDef("ID", "id"),
            ColumnDef("Name", "name"),
            ColumnDef("Status", "status"),
            ColumnDef("Profile", "profile"),
            ColumnDef("vCPUs", "vcpu", "number"),
            ColumnDef("Memory (GB)", "memory", "number"),
            ColumnDef("Zone", "zone"),
            ColumnDef("VPC", "vpcName"),
            ColumnDef("Primary IP", "primaryIp"),
            ColumnDef("Region", "region"),
            ColumnDef("Created", "created_at", "date"),
            ColumnDef("Resource Group", "resourceGroup"),
        ],
    ),
    "vpcBareMetalServers": ResourceSchema(
        worksheet_name="vVpcBareMetal",
        domain="vpc",
        resource_type="vpcBareMetalServers",
        columns=[
            ColumnDef("ID", "id"),
            ColumnDef("Name", "name"),
            ColumnDef("Status", "status"),
            ColumnDef("Profile", "profile"),
            ColumnDef("Zone", "zone"),
            ColumnDef("VPC", "vpcName"),
            ColumnDef("Region", "region"),
            ColumnDef("Created", "created_at", "date"),
            ColumnDef("Resource Group", "resourceGroup"),
        ],
    ),
    "vpcDedicatedHosts": ResourceSchema(
        worksheet_name="vVpcDedicatedHosts",
        domain="vpc",
        resource_type="vpcDedicatedHosts",
        columns=[
            ColumnDef("ID", "id"),
            ColumnDef("Name", "name"),
            ColumnDef("State", "state"),
            ColumnDef("Profile", "profile"),
            ColumnDef("Zone", "zone"),
            ColumnDef("vCPUs", "vcpu", "number"),
            ColumnDef("Memory (GB)", "memory", "number"),
            ColumnDef("Instances", "instanceCount", "number"),
            ColumnDef("Region", "region"),
            ColumnDef("Created", "created_at", "date"),
        ],
    ),
    "vpcPlacementGroups": ResourceSchema(
        worksheet_name="vVpcPlacementGroups",
        domain="vpc",
        resource_type="vpcPlacementGroups",
        columns=[
            ColumnDef("ID", "id"),
            ColumnDef("Name", "name"),
            ColumnDef("Strategy", "strategy"),
            ColumnDef("Region", "region"),
            ColumnDef("Created", "created_at", "date"),
            ColumnDef("Resource Group", "resourceGroup"),
        ],
    ),
    "vpcs": ResourceSchema(
        worksheet_name="vVpcs",
        domain="vpc",
        resource_type="vpcs",
        columns=[
            ColumnDef("ID", "id"),
            ColumnDef("Name", "name"),
            ColumnDef("Status", "status"),
            ColumnDef("Classic Access", "classicAccess", "boolean"),
            ColumnDef("Region", "region"),
            ColumnDef("Created", "created_at", "date"),
            ColumnDef("Resource Group", "resourceGroup"),
        ],
    ),
    "vpcSubnets": ResourceSchema(
        worksheet_name="vVpcSubnets",
        domain="vpc",
        resource_type="vpcSubnets",
        columns=[
            ColumnDef("ID", "id"),
            ColumnDef("Name", "name"),
            ColumnDef("Status", "status"),
            ColumnDef("CIDR", "cidr"),
            ColumnDef("Available IPs", "availableIps", "number"),
            ColumnDef("Total IPs", "totalIps", "number"),
            ColumnDef("Zone", "zone"),
            ColumnDef("VPC", "vpcName"),
            ColumnDef("Region", "region"),
            ColumnDef("Created", "created_at", "date"),
        ],
    ),
    "vpcSecurityGroups": ResourceSchema(
        worksheet_name="vVpcSecurityGroups",
        domain="vpc",
        resource_type="vpcSecurityGroups",
        columns=[
            ColumnDef("ID", "id"),
            ColumnDef("Name", "name"),
            ColumnDef("VPC", "vpcName"),
            ColumnDef("Rules", "ruleCount", "number"),
            ColumnDef("Targets", "targetCount", "number"),
            ColumnDef("Region", "region"),
            ColumnDef("Created", "created_at", "date"),
        ],
    ),
    "vpcFloatingIps": ResourceSchema(
        worksheet_name="vVpcFloatingIps",
        domain="vpc",
        resource_type="vpcFloatingIps",
        columns=[
            ColumnDef("ID", "id"),
            ColumnDef("Name", "name"),
            ColumnDef("Address", "address"),
            ColumnDef("Status", "status"),
            ColumnDef("Target", "target"),
            ColumnDef("Zone", "zone"),
            ColumnDef("Region", "region"),
            ColumnDef("Created", "created_at", "date"),
        ],
    ),
    "vpcPublicGateways": ResourceSchema(
        worksheet_name="vVpcPublicGateways",
        domain="vpc",
        resource_type="vpcPublicGateways",
        columns=[
            ColumnDef("ID", "id"),
            ColumnDef("Name", "name"),
            ColumnDef("Status", "status"),
            ColumnDef("VPC", "vpcName"),
            ColumnDef("Floating IP", "floatingIp"),
            ColumnDef("Zone", "zone"),
            ColumnDef("Region", "region"),
            ColumnDef("Created", "created_at", "date"),
        ],
    ),
    "vpcNetworkAcls": ResourceSchema(
        worksheet_name="vVpcNetworkAcls",
        domain="vpc",
        resource_type="vpcNetworkAcls",
        columns=[
            ColumnDef("ID", "id"),
            ColumnDef("Name", "name"),
            ColumnDef("VPC", "vpcName"),
            ColumnDef("Rules", "ruleCount", "number"),
            ColumnDef("Subnets", "subnetCount", "number"),
            ColumnDef("Region", "region"),
            ColumnDef("Created", "created_at", "date"),
        ],
    ),
    "vpcLoadBalancers": ResourceSchema(
        worksheet_name="vVpcLoadBalancers",
        domain="vpc",
        resource_type="vpcLoadBalancers",
        columns=[
            ColumnDef("ID", "id"),
            ColumnDef("Name", "name"),
            ColumnDef("Hostname", "hostname"),
            ColumnDef("Public", "isPublic", "boolean"),
            ColumnDef("Operating Status", "operatingStatus"),
            ColumnDef("Provisioning Status", "provisioningStatus"),
            ColumnDef("Region", "region"),
            ColumnDef("Created", "created_at", "date"),
        ],
    ),
    "vpcVpnGateways": ResourceSchema(
        worksheet_name="vVpcVpnGateways",
        domain="vpc",
        resource_type="vpcVpnGateways",
        columns=[
            ColumnDef("ID", "id"),
            ColumnDef("Name", "name"),
            ColumnDef("Status", "status"),
            ColumnDef("Mode", "mode"),
            ColumnDef("Subnet", "subnet"),
            ColumnDef("Region", "region"),
            ColumnDef("Created", "created_at", "date"),
        ],
    ),
    "transitGateways": ResourceSchema(
        worksheet_name="vTransitGateways",
        domain="vpc",
        resource_type="transitGateways",
        columns=[
            ColumnDef("ID", "id"),
            ColumnDef("Name", "name"),
            ColumnDef("Status", "status"),
            ColumnDef("Location", "location"),
            ColumnDef("Routing Scope", "routingScope"),
            ColumnDef("Resource Group", "resourceGroup"),
            ColumnDef("Created", "created_at", "date"),
        ],
    ),
    "transitGatewayConnections": ResourceSchema(
        worksheet_name="vTGConnections",
        domain="vpc",
        resource_type="transitGatewayConnections",
        columns=[
            ColumnDef("ID", "id"),
            ColumnDef("Name", "name"),
            ColumnDef("Status", "status"),
            ColumnDef("Network Type", "networkType"),
            ColumnDef("Transit Gateway", "transitGatewayName"),
            ColumnDef("Network ID", "networkId"),
            ColumnDef("Ownership", "ownershipType"),
            ColumnDef("Created", "created_at", "date"),
        ],
    ),
    "directLinkGateways": ResourceSchema(
        worksheet_name="vDirectLinkGateways",
        domain="vpc",
        resource_type="directLinkGateways",
        columns=[
            ColumnDef("ID", "id"),
            ColumnDef("Name", "name"),
            ColumnDef("Type", "type"),
            ColumnDef("Speed (Mbps)", "speedMbps", "number"),
            ColumnDef("Location", "locationName"),
            ColumnDef("BGP Status", "bgpStatus"),
            ColumnDef("Operational Status", "operationalStatus"),
            ColumnDef("Global", "global", "boolean"),
            ColumnDef("Resource Group", "resourceGroup"),
            ColumnDef("Created", "created_at", "date"),
        ],
    ),
    "directLinkVirtualConnections": ResourceSchema(
        worksheet_name="vDLVirtualConns",
        domain="vpc",
        resource_type="directLinkVirtualConnections",
        columns=[
            ColumnDef("ID", "id"),
            ColumnDef("Name", "name"),
            ColumnDef("Status", "status"),
            ColumnDef("Type", "type"),
            ColumnDef("Gateway", "gatewayName"),
            ColumnDef("Network ID", "networkId"),
            ColumnDef("Network Account", "networkAccountId"),
            ColumnDef("Created", "created_at", "date"),
        ],
    ),
    "vpnGatewayConnections": ResourceSchema(
        worksheet_name="vVpnGwConns",
        domain="vpc",
        resource_type="vpnGatewayConnections",
        columns=[
            ColumnDef("ID", "id"),
            ColumnDef("Name", "name"),
            ColumnDef("Status", "status"),
            ColumnDef("Mode", "mode"),
            ColumnDef("VPN Gateway", "vpnGatewayName"),
            ColumnDef("Peer Address", "peerAddress"),
            ColumnDef("Local CIDRs", "localCidrs"),
            ColumnDef("Peer CIDRs", "peerCidrs"),
            ColumnDef("Region", "region"),
            ColumnDef("Created", "created_at", "date"),
        ],
    ),
    "vpcEndpointGateways": ResourceSchema(
        worksheet_name="vVpcEndpointGateways",
        domain="vpc",
        resource_type="vpcEndpointGateways",
        columns=[
            ColumnDef("ID", "id"),
            ColumnDef("Name", "name"),
            ColumnDef("Lifecycle State", "lifecycleState"),
            ColumnDef("Health State", "healthState"),
            ColumnDef("Target", "target"),
            ColumnDef("VPC", "vpcName"),
            ColumnDef("Region", "region"),
            ColumnDef("Created", "created_at", "date"),
        ],
    ),
    "vpcRoutingTables": ResourceSchema(
        worksheet_name="vVpcRoutingTables",
        domain="vpc",
        resource_type="vpcRoutingTables",
        columns=[
            ColumnDef("ID", "id"),
            ColumnDef("Name", "name"),
            ColumnDef("VPC", "vpcName"),
            ColumnDef("Default", "isDefault", "boolean"),
            ColumnDef("Status", "lifecycleState"),
            ColumnDef("Routes", "routeCount", "number"),
            ColumnDef("Subnets", "subnets"),
            ColumnDef("Region", "region"),
            ColumnDef("Created", "created_at", "date"),
        ],
    ),
    "vpcRoutes": ResourceSchema(
        worksheet_name="vVpcRoutes",
        domain="vpc",
        resource_type="vpcRoutes",
        columns=[
            ColumnDef("ID", "id"),
            ColumnDef("Name", "name"),
            ColumnDef("Routing Table", "routingTableName"),
            ColumnDef("VPC", "vpcName"),
            ColumnDef("Destination CIDR", "destination"),
            ColumnDef("Action", "action"),
            ColumnDef("Next Hop Type", "nextHopType"),
            ColumnDef("Next Hop Target", "nextHopTarget"),
            ColumnDef("Zone", "zone"),
            ColumnDef("Priority", "priority", "number"),
            ColumnDef("Origin", "origin"),
            ColumnDef("Region", "region"),
            ColumnDef("Created", "created_at", "date"),
        ],
    ),
    "vpcVolumes": ResourceSchema(
        worksheet_name="vVpcVolumes",
        domain="vpc",
        resource_type="vpcVolumes",
        columns=[
            ColumnDef("ID", "id"),
            ColumnDef("Name", "name"),
            ColumnDef("Status", "status"),
            ColumnDef("Capacity (GB)", "capacity", "number"),
            ColumnDef("IOPS", "iops", "number"),
            ColumnDef("Profile", "profile"),
            ColumnDef("Encryption", "encryption"),
            ColumnDef("Zone", "zone"),
            ColumnDef("Region", "region"),
            ColumnDef("Created", "created_at", "date"),
        ],
    ),
    "vpcSshKeys": ResourceSchema(
        worksheet_name="vVpcSshKeys",
        domain="vpc",
        resource_type="vpcSshKeys",
        columns=[
            ColumnDef("ID", "id"),
            ColumnDef("Name", "name"),
            ColumnDef("Type", "type"),
            ColumnDef("Fingerprint", "fingerprint"),
            ColumnDef("Length", "length", "number"),
            ColumnDef("Region", "region"),
            ColumnDef("Created", "created_at", "date"),
        ],
    ),
    "vpcImages": ResourceSchema(
        worksheet_name="vVpcImages",
        domain="vpc",
        resource_type="vpcImages",
        columns=[
            ColumnDef("ID", "id"),
            ColumnDef("Name", "name"),
            ColumnDef("Status", "status"),
            ColumnDef("OS", "os"),
            ColumnDef("Architecture", "architecture"),
            ColumnDef("Region", "region"),
            ColumnDef("Created", "created_at", "date"),
        ],
    ),
    "vpcFlowLogCollectors": ResourceSchema(
        worksheet_name="vVpcFlowLogs",
        domain="vpc",
        resource_type="vpcFlowLogCollectors",
        columns=[
            ColumnDef("ID", "id"),
            ColumnDef("Name", "name"),
            ColumnDef("Active", "active", "boolean"),
            ColumnDef("Lifecycle State", "lifecycleState"),
            ColumnDef("Target", "target"),
            ColumnDef("Storage Bucket", "storageBucket"),
            ColumnDef("Region", "region"),
            ColumnDef("Created", "created_at", "date"),
        ],
    ),
}


# ──────────────────────────────────────────────
# POWERVS INFRASTRUCTURE SCHEMAS (~22 types)
# ──────────────────────────────────────────────

POWERVS_SCHEMAS: dict[str, ResourceSchema] = {
    "pvsInstances": ResourceSchema(
        worksheet_name="pPvsInstances",
        domain="powervs",
        resource_type="pvsInstances",
        columns=[
            ColumnDef("ID", "pvmInstanceID"),
            ColumnDef("Name", "serverName"),
            ColumnDef("Status", "status"),
            ColumnDef("System Type", "sysType"),
            ColumnDef("Processors", "processors", "number"),
            ColumnDef("Proc Type", "procType"),
            ColumnDef("Memory (GB)", "memory", "number"),
            ColumnDef("OS Type", "osType"),
            ColumnDef("Primary IP", "primaryIp"),
            ColumnDef("Storage Type", "storageType"),
            ColumnDef("Workspace", "workspace"),
            ColumnDef("Zone", "zone"),
            ColumnDef("Created", "creationDate", "date"),
        ],
    ),
    "pvsSharedProcessorPools": ResourceSchema(
        worksheet_name="pPvsSPPools",
        domain="powervs",
        resource_type="pvsSharedProcessorPools",
        columns=[
            ColumnDef("ID", "id"),
            ColumnDef("Name", "name"),
            ColumnDef("Host Group", "hostGroup"),
            ColumnDef("Reserved Cores", "reservedCores", "number"),
            ColumnDef("Allocated Cores", "allocatedCores", "number"),
            ColumnDef("Available Cores", "availableCores", "number"),
            ColumnDef("Instances", "instanceCount", "number"),
            ColumnDef("Workspace", "workspace"),
            ColumnDef("Zone", "zone"),
        ],
    ),
    "pvsPlacementGroups": ResourceSchema(
        worksheet_name="pPvsPlacementGrps",
        domain="powervs",
        resource_type="pvsPlacementGroups",
        columns=[
            ColumnDef("ID", "id"),
            ColumnDef("Name", "name"),
            ColumnDef("Policy", "policy"),
            ColumnDef("Members", "memberCount", "number"),
            ColumnDef("Workspace", "workspace"),
            ColumnDef("Zone", "zone"),
        ],
    ),
    "pvsHostGroups": ResourceSchema(
        worksheet_name="pPvsHostGroups",
        domain="powervs",
        resource_type="pvsHostGroups",
        columns=[
            ColumnDef("ID", "id"),
            ColumnDef("Name", "name"),
            ColumnDef("Hosts", "hostCount", "number"),
            ColumnDef("Secondaries", "secondaryCount", "number"),
            ColumnDef("Workspace", "workspace"),
            ColumnDef("Zone", "zone"),
        ],
    ),
    "pvsNetworks": ResourceSchema(
        worksheet_name="pPvsNetworks",
        domain="powervs",
        resource_type="pvsNetworks",
        columns=[
            ColumnDef("ID", "networkID"),
            ColumnDef("Name", "name"),
            ColumnDef("Type", "type"),
            ColumnDef("VLAN ID", "vlanID", "number"),
            ColumnDef("CIDR", "cidr"),
            ColumnDef("Gateway", "gateway"),
            ColumnDef("MTU", "mtu", "number"),
            ColumnDef("Workspace", "workspace"),
            ColumnDef("Zone", "zone"),
        ],
    ),
    "pvsNetworkPorts": ResourceSchema(
        worksheet_name="pPvsNetPorts",
        domain="powervs",
        resource_type="pvsNetworkPorts",
        columns=[
            ColumnDef("Port ID", "portID"),
            ColumnDef("IP Address", "ipAddress"),
            ColumnDef("MAC Address", "macAddress"),
            ColumnDef("Status", "status"),
            ColumnDef("Network", "networkName"),
            ColumnDef("Instance", "pvmInstanceName"),
            ColumnDef("Workspace", "workspace"),
            ColumnDef("Zone", "zone"),
        ],
    ),
    "pvsNetworkSecurityGroups": ResourceSchema(
        worksheet_name="pPvsNSGs",
        domain="powervs",
        resource_type="pvsNetworkSecurityGroups",
        columns=[
            ColumnDef("ID", "id"),
            ColumnDef("Name", "name"),
            ColumnDef("Rules", "ruleCount", "number"),
            ColumnDef("Members", "memberCount", "number"),
            ColumnDef("Workspace", "workspace"),
            ColumnDef("Zone", "zone"),
        ],
    ),
    "pvsCloudConnections": ResourceSchema(
        worksheet_name="pPvsCloudConns",
        domain="powervs",
        resource_type="pvsCloudConnections",
        columns=[
            ColumnDef("ID", "cloudConnectionID"),
            ColumnDef("Name", "name"),
            ColumnDef("Speed (Mbps)", "speed", "number"),
            ColumnDef("Global Routing", "globalRouting", "boolean"),
            ColumnDef("GRE Tunnel", "greEnabled", "boolean"),
            ColumnDef("Transit Enabled", "transitEnabled", "boolean"),
            ColumnDef("Networks", "networkCount", "number"),
            ColumnDef("Workspace", "workspace"),
            ColumnDef("Zone", "zone"),
        ],
    ),
    "pvsDhcpServers": ResourceSchema(
        worksheet_name="pPvsDhcp",
        domain="powervs",
        resource_type="pvsDhcpServers",
        columns=[
            ColumnDef("ID", "id"),
            ColumnDef("Status", "status"),
            ColumnDef("Network ID", "networkId"),
            ColumnDef("Network", "networkName"),
            ColumnDef("Workspace", "workspace"),
            ColumnDef("Zone", "zone"),
        ],
    ),
    "pvsVpnConnections": ResourceSchema(
        worksheet_name="pPvsVpnConns",
        domain="powervs",
        resource_type="pvsVpnConnections",
        columns=[
            ColumnDef("ID", "id"),
            ColumnDef("Name", "name"),
            ColumnDef("Status", "status"),
            ColumnDef("Mode", "mode"),
            ColumnDef("Peer Address", "peerAddress"),
            ColumnDef("Local Subnets", "localSubnets"),
            ColumnDef("Peer Subnets", "peerSubnets"),
            ColumnDef("Workspace", "workspace"),
            ColumnDef("Zone", "zone"),
        ],
    ),
    "pvsIkePolicies": ResourceSchema(
        worksheet_name="pPvsIkePolicies",
        domain="powervs",
        resource_type="pvsIkePolicies",
        columns=[
            ColumnDef("ID", "id"),
            ColumnDef("Name", "name"),
            ColumnDef("IKE Version", "version", "number"),
            ColumnDef("Encryption", "encryption"),
            ColumnDef("DH Group", "dhGroup", "number"),
            ColumnDef("Authentication", "authentication"),
            ColumnDef("Workspace", "workspace"),
            ColumnDef("Zone", "zone"),
        ],
    ),
    "pvsIpsecPolicies": ResourceSchema(
        worksheet_name="pPvsIpsecPolicies",
        domain="powervs",
        resource_type="pvsIpsecPolicies",
        columns=[
            ColumnDef("ID", "id"),
            ColumnDef("Name", "name"),
            ColumnDef("Encryption", "encryption"),
            ColumnDef("DH Group", "dhGroup", "number"),
            ColumnDef("Authentication", "authentication"),
            ColumnDef("PFS", "pfs", "boolean"),
            ColumnDef("Workspace", "workspace"),
            ColumnDef("Zone", "zone"),
        ],
    ),
    "pvsVolumes": ResourceSchema(
        worksheet_name="pPvsVolumes",
        domain="powervs",
        resource_type="pvsVolumes",
        columns=[
            ColumnDef("ID", "volumeID"),
            ColumnDef("Name", "name"),
            ColumnDef("State", "state"),
            ColumnDef("Size (GB)", "size", "number"),
            ColumnDef("Disk Type", "diskType"),
            ColumnDef("Bootable", "bootable", "boolean"),
            ColumnDef("Shareable", "shareable", "boolean"),
            ColumnDef("Attached To", "pvmInstanceName"),
            ColumnDef("Workspace", "workspace"),
            ColumnDef("Zone", "zone"),
            ColumnDef("Created", "creationDate", "date"),
        ],
    ),
    "pvsVolumeGroups": ResourceSchema(
        worksheet_name="pPvsVolGroups",
        domain="powervs",
        resource_type="pvsVolumeGroups",
        columns=[
            ColumnDef("ID", "id"),
            ColumnDef("Name", "name"),
            ColumnDef("Status", "status"),
            ColumnDef("Consistency Group", "consistencyGroupName"),
            ColumnDef("Volumes", "volumeCount", "number"),
            ColumnDef("Replication", "replicationEnabled", "boolean"),
            ColumnDef("Workspace", "workspace"),
            ColumnDef("Zone", "zone"),
        ],
    ),
    "pvsSnapshots": ResourceSchema(
        worksheet_name="pPvsSnapshots",
        domain="powervs",
        resource_type="pvsSnapshots",
        columns=[
            ColumnDef("ID", "snapshotID"),
            ColumnDef("Name", "name"),
            ColumnDef("Status", "status"),
            ColumnDef("% Complete", "percentComplete", "number"),
            ColumnDef("Instance", "pvmInstanceName"),
            ColumnDef("Volumes", "volumeCount", "number"),
            ColumnDef("Workspace", "workspace"),
            ColumnDef("Zone", "zone"),
            ColumnDef("Created", "creationDate", "date"),
        ],
    ),
    "pvsSshKeys": ResourceSchema(
        worksheet_name="pPvsSshKeys",
        domain="powervs",
        resource_type="pvsSshKeys",
        columns=[
            ColumnDef("Name", "name"),
            ColumnDef("Key (truncated)", "sshKey"),
            ColumnDef("Created", "creationDate", "date"),
            ColumnDef("Workspace", "workspace"),
            ColumnDef("Zone", "zone"),
        ],
    ),
    "pvsWorkspaces": ResourceSchema(
        worksheet_name="pPvsWorkspaces",
        domain="powervs",
        resource_type="pvsWorkspaces",
        columns=[
            ColumnDef("GUID", "guid"),
            ColumnDef("Name", "name"),
            ColumnDef("Zone", "zone"),
            ColumnDef("Region", "region"),
            ColumnDef("Resource Group", "resourceGroupName"),
            ColumnDef("State", "state"),
            ColumnDef("Created", "createdAt", "date"),
        ],
    ),
    "pvsSystemPools": ResourceSchema(
        worksheet_name="pPvsSystemPools",
        domain="powervs",
        resource_type="pvsSystemPools",
        columns=[
            ColumnDef("System Type", "type"),
            ColumnDef("Shared Core Ratio", "sharedCoreRatio"),
            ColumnDef("Max Available Cores", "maxAvailable", "number"),
            ColumnDef("Max Available Memory (GB)", "maxMemory", "number"),
            ColumnDef("Core:Memory Ratio", "coreMemoryRatio", "number"),
            ColumnDef("Workspace", "workspace"),
            ColumnDef("Zone", "zone"),
        ],
    ),
    "pvsSapProfiles": ResourceSchema(
        worksheet_name="pPvsSapProfiles",
        domain="powervs",
        resource_type="pvsSapProfiles",
        columns=[
            ColumnDef("Profile ID", "profileID"),
            ColumnDef("Type", "type"),
            ColumnDef("Cores", "cores", "number"),
            ColumnDef("Memory (GB)", "memory", "number"),
            ColumnDef("SAPS", "saps", "number"),
            ColumnDef("Certified", "certified", "boolean"),
            ColumnDef("Workspace", "workspace"),
            ColumnDef("Zone", "zone"),
        ],
    ),
    "pvsImages": ResourceSchema(
        worksheet_name="pPvsImages",
        domain="powervs",
        resource_type="pvsImages",
        columns=[
            ColumnDef("ID", "imageID"),
            ColumnDef("Name", "name"),
            ColumnDef("State", "state"),
            ColumnDef("OS", "operatingSystem"),
            ColumnDef("Architecture", "architecture"),
            ColumnDef("Size (GB)", "size", "number"),
            ColumnDef("Storage Type", "storageType"),
            ColumnDef("Workspace", "workspace"),
            ColumnDef("Zone", "zone"),
            ColumnDef("Created", "creationDate", "date"),
        ],
    ),
    "pvsStockImages": ResourceSchema(
        worksheet_name="pPvsStockImages",
        domain="powervs",
        resource_type="pvsStockImages",
        columns=[
            ColumnDef("ID", "imageID"),
            ColumnDef("Name", "name"),
            ColumnDef("State", "state"),
            ColumnDef("OS", "operatingSystem"),
            ColumnDef("Architecture", "architecture"),
            ColumnDef("Storage Type", "storageType"),
            ColumnDef("Workspace", "workspace"),
            ColumnDef("Zone", "zone"),
        ],
    ),
    "pvsEvents": ResourceSchema(
        worksheet_name="pPvsEvents",
        domain="powervs",
        resource_type="pvsEvents",
        columns=[
            ColumnDef("Event ID", "eventID"),
            ColumnDef("Action", "action"),
            ColumnDef("Level", "level"),
            ColumnDef("Message", "message"),
            ColumnDef("Resource", "resource"),
            ColumnDef("User", "user"),
            ColumnDef("Timestamp", "timestamp", "date"),
            ColumnDef("Workspace", "workspace"),
            ColumnDef("Zone", "zone"),
        ],
    ),
}


# ──────────────────────────────────────────────
# VMWARE INFRASTRUCTURE SCHEMAS
# ──────────────────────────────────────────────

VMWARE_SCHEMAS: dict[str, ResourceSchema] = {
    "vmwareInstances": ResourceSchema(
        worksheet_name="vVMwareInstances",
        domain="vmware",
        resource_type="vmwareInstances",
        columns=[
            ColumnDef("ID", "id"),
            ColumnDef("Name", "name"),
            ColumnDef("Location", "location"),
            ColumnDef("Status", "status"),
            ColumnDef("Deploy Type", "deployType"),
            ColumnDef("Domain Type", "domainType"),
            ColumnDef("NSX Type", "nsxType"),
            ColumnDef("Version", "version"),
            ColumnDef("Clusters", "clusterCount", "number"),
            ColumnDef("Creator", "creator"),
            ColumnDef("CRN", "crn"),
        ],
    ),
    "vmwareClusters": ResourceSchema(
        worksheet_name="vVMwareClusters",
        domain="vmware",
        resource_type="vmwareClusters",
        columns=[
            ColumnDef("ID", "id"),
            ColumnDef("Name", "name"),
            ColumnDef("Location", "location"),
            ColumnDef("Status", "status"),
            ColumnDef("Host Count", "hostCount", "number"),
            ColumnDef("Storage Type", "storageType"),
            ColumnDef("Instance ID", "instanceId"),
        ],
    ),
    "vmwareHosts": ResourceSchema(
        worksheet_name="vVMwareHosts",
        domain="vmware",
        resource_type="vmwareHosts",
        columns=[
            ColumnDef("Hostname", "hostname"),
            ColumnDef("Public IP", "publicIp"),
            ColumnDef("Private IP", "privateIp"),
            ColumnDef("Status", "status"),
            ColumnDef("Server ID", "serverId"),
            ColumnDef("Version", "version"),
            ColumnDef("Memory (GB)", "memory", "number"),
            ColumnDef("CPUs", "cpus", "number"),
            ColumnDef("Cluster", "clusterName"),
            ColumnDef("Location", "location"),
            ColumnDef("Instance ID", "instanceId"),
            ColumnDef("Cluster ID", "clusterId"),
        ],
    ),
    "vmwareVlans": ResourceSchema(
        worksheet_name="vVMwareVlans",
        domain="vmware",
        resource_type="vmwareVlans",
        columns=[
            ColumnDef("VLAN Number", "vlanNumber", "number"),
            ColumnDef("Name", "name"),
            ColumnDef("Purpose", "purpose"),
            ColumnDef("Primary Router", "primaryRouter"),
            ColumnDef("Cluster", "clusterName"),
            ColumnDef("Location", "location"),
            ColumnDef("Instance ID", "instanceId"),
            ColumnDef("Cluster ID", "clusterId"),
        ],
    ),
    "vmwareSubnets": ResourceSchema(
        worksheet_name="vVMwareSubnets",
        domain="vmware",
        resource_type="vmwareSubnets",
        columns=[
            ColumnDef("CIDR", "cidr"),
            ColumnDef("Netmask", "netmask"),
            ColumnDef("Gateway", "gateway"),
            ColumnDef("Type", "type"),
            ColumnDef("Purpose", "purpose"),
            ColumnDef("VLAN", "vlanNumber", "number"),
            ColumnDef("VLAN Name", "vlanName"),
            ColumnDef("Cluster", "clusterName"),
            ColumnDef("Location", "location"),
            ColumnDef("Instance ID", "instanceId"),
        ],
    ),
    "directorSites": ResourceSchema(
        worksheet_name="vDirectorSites",
        domain="vmware",
        resource_type="directorSites",
        columns=[
            ColumnDef("ID", "id"),
            ColumnDef("Name", "name"),
            ColumnDef("Status", "status"),
            ColumnDef("Region", "region"),
            ColumnDef("PVDCs", "pvdcCount", "number"),
            ColumnDef("Created", "createdAt", "date"),
        ],
    ),
    "pvdcs": ResourceSchema(
        worksheet_name="vPVDCs",
        domain="vmware",
        resource_type="pvdcs",
        columns=[
            ColumnDef("ID", "id"),
            ColumnDef("Name", "name"),
            ColumnDef("Datacenter", "datacenter"),
            ColumnDef("Status", "status"),
            ColumnDef("Provider Type", "providerType"),
            ColumnDef("Clusters", "clusterCount", "number"),
            ColumnDef("Director Site ID", "directorSiteId"),
        ],
    ),
    "vcfClusters": ResourceSchema(
        worksheet_name="vVCFClusters",
        domain="vmware",
        resource_type="vcfClusters",
        columns=[
            ColumnDef("ID", "id"),
            ColumnDef("Name", "name"),
            ColumnDef("Host Count", "hostCount", "number"),
            ColumnDef("Status", "status"),
            ColumnDef("Datacenter", "datacenter"),
            ColumnDef("Host Profile", "hostProfile"),
            ColumnDef("Storage Type", "storageType"),
            ColumnDef("PVDC ID", "pvdcId"),
        ],
    ),
    "vdcs": ResourceSchema(
        worksheet_name="vVDCs",
        domain="vmware",
        resource_type="vdcs",
        columns=[
            ColumnDef("ID", "id"),
            ColumnDef("Name", "name"),
            ColumnDef("Status", "status"),
            ColumnDef("Director Site", "directorSiteName"),
            ColumnDef("CPU", "cpu"),
            ColumnDef("RAM", "ram"),
            ColumnDef("Disk", "disk"),
            ColumnDef("Region", "region"),
            ColumnDef("Type", "type"),
            ColumnDef("Created", "createdAt", "date"),
        ],
    ),
    "multitenantSites": ResourceSchema(
        worksheet_name="vMultitenantSites",
        domain="vmware",
        resource_type="multitenantSites",
        columns=[
            ColumnDef("ID", "id"),
            ColumnDef("Name", "name"),
            ColumnDef("Region", "region"),
            ColumnDef("PVDCs", "pvdcCount", "number"),
        ],
    ),
    "vmwareCrossReferences": ResourceSchema(
        worksheet_name="vVMwareCrossReferences",
        domain="vmware",
        resource_type="vmwareCrossReferences",
        columns=[
            ColumnDef("Classic Resource Type", "classicResourceType"),
            ColumnDef("Classic Resource ID", "classicResourceId"),
            ColumnDef("Classic Resource Name", "classicResourceName"),
            ColumnDef("VMware Role", "vmwareRole"),
            ColumnDef("VMware Resource Type", "vmwareResourceType"),
            ColumnDef("VMware Resource ID", "vmwareResourceId"),
            ColumnDef("VMware Resource Name", "vmwareResourceName"),
        ],
    ),
}


ALL_SCHEMAS = {**CLASSIC_SCHEMAS, **VPC_SCHEMAS, **POWERVS_SCHEMAS, **VMWARE_SCHEMAS}
